sudo: required
services:
  - docker

before_install:
  - docker build -t mevis3249/udemy-docker-course -f Dockerfile.dev . 

script:
  - docker run mevis3249/udemy-docker-course npm run test -- --coverage