#Travis Config 3
sudo: required
services:
  - docker

before_install:
  - docker build -t mevismishima/udemy-docker-course -f Dockerfile.dev .

script:
  - docker run -e CI=true mevismishima/udemy-docker-course npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-883262425986"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
