sudo: required
services:
  - docker

before_install:
  - docker build -t MevisMishima/udemy-docker-course -f Dockerfile.dev . 

script:
  - docker run -e CI=true mevismishima/udemy-docker-course npm run test

deploy:
  provider: azure_web_apps
  username: $AZURE_WA_USERNAME
  password: $AZURE_WA_PASSWORD
  site: "https://udemy-test.azurewebsites.net/"