sudo: required
services:
  - docker

before_install:
  - docker build -t mevis3249/udemy-docker-course -f Dockerfile.prod . 

script:
  - docker run -e CI=true mevis3249/udemy-docker-course npm run test

deploy:
  provider: azure_web_apps
  username: $AZURE_WA_USERNAME
  password: $AZURE_WA_PASSWORD
  site: "https://udemy-test.azurewebsites.net/"